### ISSUE TITLE
BBFC submission template

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#105]
The "Original complaint" field seems to be populated by the details field supplied by the Admin user, eg:

"Vodafone should have unblocked this site, but have not looked at the request."

This should be the details from the orginal complaint to the ISP by the Blocked front end user.

> A request to unblock the site was submitted to the mobile operator, Vodafone.
> 
> Original complaint:
> 
> Vodafone should have unblocked this site, but have not looked at the request.
> 
> Mobile operator response:
> 
> Hello.
> 
> Thanks for getting in touch. Just to confirm, we’ve received your email and we’ll be in touch shortly.
> 
> Please note: This email address is only for reporting the misclassification of a website.
> 
> Vodafone use a Classification Framework designed by the British Board of Film Classification (BBFC) to filter content available via mobile networks. The BBFC will investigate misclassification requests if we cannot resolve your request. Please visit the BBFC’s website for more information on how to refer your misclassification request to the BBFC.
> 
> Want to remove your age-restricted content bar?
> Simply follow our handy step-by-step guide here.
> 
> Need help with something else?
> For answers to the most common questions, head over to our support page. Alternatively, you can chat to us online, visit us at your local store, or call us on 191 free from any Vodafone mobile (0333 304 0191 from any other phone – standard call charges apply).
> 
> Thank you
> The Customer Care Team

**Comment by dantheta** [comment]
Oops!  Sorry about that.  I've re-ordered the fields and adjusted the headings so that they're more consistent.

**Comment by dantheta** [comment]
I'll rework the BBFC escalation form so that it displays:

* The original user's unblock request message
* The ISP response (editable, to clear up email formatting)
* Admin comments for BBFC (editable)

These will be carried through to the email that is sent.

**Comment by dantheta** [comment]
The BBFC escalation email has been reformatted so that all four customisable fields (original complaint, ISP response, admin comments and additional contact information) are submitted in the main body and recorded as an outgoing email.

**Comment by JimKillock** [comment]
Looks good, will close when we resolve the bug on the form so I can verify what has gone through the email
