### ISSUE TITLE
New functionality: Sort classified ISP reports by reviewer & date

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#106]
We are inducting new volunteers to classify reports going back to March 2019. It would be very helpful if we could sort through classified reports by reviewer so I can check their work and give individual feedback. is this possible?

**Comment by dantheta** [comment]
Yep, that should be doable.  It could get a little bit complicated where more than one user has been involved in reviewing a report, but we can see how it goes.

**Comment by JimKillock** [comment]
@dantheta if we choose the reviewer who has 'closed' the report (as "blocked" / "unblocked"), perhaps that simplifies things? And then @Mike-ORG you can review items that are completed.

**Comment by dantheta** [comment]
This is deployed now.  The user list filter is only available to admins.

The system is now also recording the userid of the reviewer who closes a report (previously it only recorded the userid against comments in the review system).  This will be incorporated into the dropdown filter.  For the moment it's using the report/review/category comment userids.

**Comment by Mike-ORG** [comment]
Thanks Daniel I'll have a look.

**Comment by JimKillock** [comment]
@Mike-ORG how does it look?

**Comment by Mike-ORG** [comment]
Appears to be working well. I can see two of our volunteers in there which must mean they are the only ones who have been active so far, of the group of five. That sounds right because several told me they haven't started yet.
