### ISSUE TITLE
Add filter in admin section: "All mobile" and "blocked against policy"

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#107]
In the admin section, under "ISP Report Admin", add filters for:

1. All mobile operators;
2. Blocked against policy (at one or more ISPs)

Currently we can [view per ISP](https://www.blocked.org.uk/control/ispreports?state=reviewed&network=Vodafone); this will help us isolate reports that need to be sent on to BBFC.

**Comment by dantheta** [comment]
Mobile network filter added

**Comment by dantheta** [comment]
policy match filter added, with a simple choice of matches / does not match.  ISP reports that have not had a policy match status assigned will not appear in either filter view.

**Comment by JimKillock** [comment]
Ok, I tried this. The "policy match (No)" filter seems to include sites where a review has not looked and not therefore concluded a policy match. It should filter in both cases for sites where a reviewer has **marked** as "policy match (yes)" or policy match (no)", and **exclude** all sites where a reviewer has not yet checked.

**Comment by dantheta** [comment]
I haven't been able to reproduce this one, I'm afraid.  The filter specifies that the matches_policy field is not empty, and must be true/false depending on which filter setting has been chosen.

If you are able to see the same thing again, please can you note an example of a report that is being incorrectly selected and the control panel URL.  I'm wondering if one of the other filters is interfering with it.

Thanks!

**Comment by JimKillock** [comment]
Thanks Dan, looks like I may have been fooled by a large number of recent reviews! Closing therefore.
