### ISSUE TITLE
BBFC submission has overwritten original response

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#108]
This [report](https://www.blocked.org.uk/site/http://gaiaguru.co.uk) is now showing the submission / comment we made to BBFC rather than the user complaint to ISPs. 

( Our submission: “Vodafone should have unblocked this site, but have not looked at the request.”)

#105 maybe related?

**Comment by dantheta** [comment]
That's fixed.  The API sends back all of the ISP reports for a URL, (which included the BBFC report) in a non-deterministic order.  The frontend uses the text from the first, which happened to be the BBFC one.  I've excluded the BBFC reports from the status response, so the original report display is restored.
