### ISSUE TITLE
BBFC submission: contact address

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#109]
On our submission form to BBFC, it says"

> Contact:  Blocked admin <blocked@openrightsgroup.org>

Please change this to the reply string, so that they respond in a way that the Blocked system records.

**Comment by dantheta** [comment]
Should be fixed now.  Was the sender/reply-to address in the email headers correct?

**Comment by JimKillock** [comment]
Hi Dan, yes, the sender and reply-to seem to be right.
