### ISSUE TITLE
Closing reports Blocked / Unblocked

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#111]
I think this should be "To be Unblocked" and "To be blocked". 

Sometimes, ISPs or BBFC say they will unblock a site, but this does not occur. The system itself can detect whether a site is blocked or not, so we should be clear we are recording the decision of the ISP / BBFC with this review flag.

**Comment by dantheta** [comment]
Would it be shorter (but hopefully still as accurate) to use "Accepted" and "Rejected" in relation to the unblock request?

This would appear in the "Close report" menu on the email display, and where the status is shown in the listing and on the ISP report page.

**Comment by dantheta** [comment]
I've gone with "Accepted" for now.  The control panel implementation URLs haven't changed, it's just a presentation change in the admin panel.

**Comment by JimKillock** [comment]
Yes this makes sense (we seem to be duplicatimng the discussion) - we do need the third option of "no reply" however.

**Comment by Mike-ORG** [comment]
A "no reply" option would be very helpful because in many cases there is no correspondence. Would the "no reply" option be available then via a different window than "Close Report"?

**Comment by Mike-ORG** [comment]
What about cases where there is an initial auto-message from the ISP saying they will review the category, but there is no follow up message? Would this be considered a no-reply? If the site is now unblocked, should it be marked as Accepted even if they didn't concede the error in writing? Or if it remains blocked, should it be marked Rejected even if they don't put it in writing?

**Comment by JimKillock** [comment]
@Mike-ORG Yes, a substantive reply is needed in order to record a decision. automated replies or promises to adjudicate would count as "no reply" if a decision wasn't added. 

Many sites get unblocked without a response as you say. This however we work out from the data, for statistical purposes, but it usually happens they rely on the same third party lists rather than because they responded to the request. But this should be handled separately to what we see from the responses.

**Comment by Mike-ORG** [comment]
Thanks @JimKillock, that makes sense. I'll explain this to the volunteers once we get the no-reply option.

@dantheta the option to close a report is only available when there is at least one message. So can we make the "close report" option available when there are no messages, so we can mark "no-reply"?

**Comment by JimKillock** [comment]
Thanks for closing the duplicates @dantheta. We can add a third flag "No decision", which hopefully is clear and covers any instances where partial responses are received.

**Comment by JimKillock** [comment]
@Mike-ORG There may be instances where an ISP makes some kind of partial reply but then does not actually resolve the complaint. I can't say I have seen any, but they may occur.

More commonly, we get auto-responses, but no decision email, and these do need to be marked as "no decision", so users do need to be able to choose the third option when emails have been received.

Ideally, "no decision" should only be available after 30 days.

**Comment by JimKillock** [comment]
(PS: "no decision" needs to be possible to escalate to BBFC if mobile.)

**Comment by dantheta** [comment]
I think that "no decision" and "no reply"  can be folded together into the same function, unless we'd want to record these separately for reporting purposes?

**Comment by JimKillock** [comment]
@dantheta yes, we can treat these as the same - I would use the label "no decision".

**Comment by JimKillock** [comment]
(PS, I closed a couple of reports as "Rejected" in order to report to BBFC but they are in in fact "No decision" so I hope that doesn't cause problems when we get the new status :)

**Comment by dantheta** [comment]
The no-decision status has been added.  I haven't put in a minimum age limit yet since there's probably some fixing up of existing data that we want to do.  The reports that were closed as "rejected" to push them to BBFC can have their status reset to "sent" and can be re-closed as "no-decision".
