### ISSUE TITLE
BBFC submission form "Error"

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#113]
I got an error on submit from [https://www.blocked.org.uk/control/ispreports/escalate/5596](https://www.blocked.org.uk/control/ispreports/escalate/5596)

**Comment by dantheta** [comment]
This error s being caused by unicode characters in the original report text.  I'll be able to fix that later on.  In the meantime, other reports sshould still be able to go through.

**Comment by JimKillock** [comment]
Hi Dan

I got the same error on https://www.blocked.org.uk/control/ispreports/escalate/5576 

The complaint appears to be blank tho, so shouldn't be a charset issue.

**Comment by dantheta** [comment]
Hopefully that's fixed now.

**Comment by JimKillock** [comment]
Great these seem to have gone through :)
