### ISSUE TITLE
"Review Categories" tab won't mark green check when updated

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#118]
This has happened a couple times, where the addition or subtraction of categories works fine but no green check on the "Review Categories" tab  appears after update.

Here is an example:
https://www.blocked.org.uk/control/ispreports/Vodafone/http://www.thisisarecording.com?tab=categories

**Comment by dantheta** [comment]
The green tick function relates to ORG categories only - assigning categorify or DMOZ categories doesn't satisfy the conditions as they are currently written, though I can change them if required.  One thing to keep in mind - if categorify categories are assigned, they might become unassigned if categorify change their criteria.

**Comment by dantheta** [comment]
I can switch the manually assigned categorify categories to their ORG counterparts, but I probably wouldn't be able to get to it until the weekend.

**Comment by JimKillock** [comment]
I think it makes sense for us to require an ORG category is assigned, does that make sense to you @Mike-ORG ?

**Comment by Mike-ORG** [comment]
Sure that makes sense, I will update the guidance and inform the volunteers.
