### ISSUE TITLE
URL status on BBFC Blocked admin

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#120]
On the "URL Status" page for BBFC reports, all of the sites listed state that the site is "blocked". Is this because BBFC isn't an ISP as such, so URLs can't be calculated as "unblocked"? 

If so, could we base the "URL Status" for BBFC on the cumulative situation at mobile ISPs - that is, if all mobile ISPs have unblocked the site, the URL should be "unblocked", otherwise, the status should be "blocked".

We have had some URLs adjudicated for unblocking by BBFC but not actioned by MNOs so this would be helpful to track.

**Comment by dantheta** [comment]
Yep, that should be doable.

**Comment by JimKillock** [comment]
Great, same issue here: https://www.blocked.org.uk/bbfc-reports – it should state "unblocked" only when *all* MNOs have unblocked the site (and we don't care about other operators).

**Comment by dantheta** [comment]
URL status in the BBFC  entries in the ISP reports summary view now reflects the MVNO unblock status for the associated URL.

**Comment by dantheta** [comment]
Urgh, the issue numbers in the commits got very messed up.  The later commits belong to #156
