### ISSUE TITLE
Auto response to Sky rejection emails

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#122]
We regularly receive a rejection email from Sky explaining that they won't doing anything unless a further response is sent.

When an email from Sky, starting "Dear" is received, and with a proper Subject line, can we send an automatic response:

> Dear Sky review team,
> 
> This is to confirm that this complaint is not from a Sky customer, but is a request for you to investigate a website incorrectly classified and blocked by your filters.
> 
> Please review the site  [ URL as plaintext] and let us know the outcome.
> 
> Sincerely,
> 
> Blocked Project on behalf of [ name ].

**Comment by dantheta** [comment]
We can also add a custom piece of text to the submission email for Sky (we currently do that for VirginMedia as well)

**Comment by JimKillock** [comment]
Both Virgin and Sky are very unresponsive currently. I'm hoping reminder emails and these responses will help, but I have also raised with their policy teams, although without results as yet.

**Comment by JimKillock** [comment]
Could we add for Sky:

This email was sent by a user of the "Blocked service", which checks websites that may be miscategorised by your adult content filters. Please note they are not normally Sky customers and do not need help switching filters off. Please treat this as an external request to review the categorisation of [website] by your filters.

**Comment by JimKillock** [comment]
I think we can close this on the assumption that the new email address will work.
