### ISSUE TITLE
Add admin search filter: By "Report Status" and "URL Status"

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#123]
Allow user to filter by "Report Status"

1. Report accepted
2. Report rejected / no response (treat as the same)

and by "URL Status"

1. Blocked
2. Unblocked

This (with the "all" mobile operators filter plus "Policy match") will allow us to identify what needs to be escalated to BBFC.

**Comment by dantheta** [comment]
That's added.  I'm hidden some of the less used status filters to make space.  We can add them back in a drop-down if they're needed again.

**Comment by JimKillock** [comment]
Thanks Dan, seems to work well!
