### ISSUE TITLE
Auto response to non-reviewed sites

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#124]
Where a site is

1. Blocked; and
2. The report is marked as "against policy"; and the report is marked as "No decision"
OR
4. Only an auto-response has been sent, OR
5. No response has been sent; AND
6. 14 days have passed

then

1. Send a reminder that the site is blocked and needs to be reviewed.

The site 'decision' flag would need to be reset when a reminder email was sent.

Reminder emails could be sent every 30 days.

**Comment by JimKillock** [comment]
Suggest we wimplement this now so that the historic, unreviewed Sky complaints get sent to the new email address.

**Comment by dantheta** [comment]
This sounds OK, though I think we should keep the no-decision status as a final state (as in, case closed).

I think while a report is open (status sent), the system can keep sending reminder emails.  The No-decision state permits a report to be escalated to BBFC, and we're soon adding a separate report-closed state to reflect that.  

In the case of escalation and any of the other closed statuses, the system should stop sending reminders.  I'm wondering if no-decision should be retained as a "close report with no reply" status, leaving the option of referring it to the BBFC.  

Changing between no-decision and sent could cause a few problems for reporting - I'd envisaged that a report goes through a set of stages from _new_ to _closed_, with no general toggling between open and closed.  I think it's OK for a report to have its status left at "open(sent)" while we still want the system to send reminders, and only set to closed(no-decision) when we want the report concluded.

**Comment by dantheta** [comment]
Sent a test run of 5 reports.  Secondary auto-replies could be an issue.
