### ISSUE TITLE
BBFC escalation breaks where report is closed as 'no decision'

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#125]
The 'escalate to BBFC' hits some kind of permission issue if a report is closed as "no decision", for instance:

https://www.blocked.org.uk/control/ispreports/escalate/5504

returns "Cannot escalate report unless report has been rejected by ISP"

**Comment by dantheta** [comment]
Oops, missed one.  Should be fixed now.

**Comment by JimKillock** [comment]
Not working for me just now at https://www.blocked.org.uk/control/ispreports/Vodafone/http://www.bestvpnserver.com

**Comment by dantheta** [comment]
OK - should be ready to retest.  It was complaining where there wasn't an ISP response email to read into the form.  For the no-decision status the ISP reply field will remain empty.  The admin can enter some explanatory description there.

**Comment by JimKillock** [comment]
Thanks Dan, seems to be working now!
