### ISSUE TITLE
Bulk close old reports

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#135]
Can we close all old reports, prior to accepting correspondence with ISPs, where the blocks are also lifted?

And add a new status of "historic closed" for these, perhaps. This doesn't need to be available from the admin interface.

**Comment by dantheta** [comment]
Updated 1280 reports which had status 'sent' and unblocked; updated 19 reports in 'pending' and unblocked.  All prior to the first email reply from ISPS.
