### ISSUE TITLE
Reveiwer users get "error" message when attempting to flag an ISP report

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#139]
Can we make it so reviewers can flag reports when they find abusive reports? I noticed I get error messages when flagging as a reviewer but it works as an admin.

**Comment by JimKillock** [comment]
I think OK to give reviewers this facility.

**Comment by dantheta** [comment]
That's been updated.

**Comment by dantheta** [comment]
tested - works as expected.

**Comment by Mike-ORG** [comment]
Excellent thanks @dantheta !
