### ISSUE TITLE
ISP reports generating error messages

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#147]
The following ISP reports lead to an error page when viewed so can't be closed out:

https://www.blocked.org.uk/control/ispreports/EE/http://courtneyx.com
https://www.blocked.org.uk/control/ispreports/BT/http://hemp.je
https://www.blocked.org.uk/control/ispreports/Three/http://pornomonkey.com
https://www.blocked.org.uk/control/ispreports/Sky/http://lovehoney.co.uk
https://www.blocked.org.uk/control/ispreports/Sky/http://realvoices.org.uk
https://www.blocked.org.uk/control/ispreports/Sky/http://ipvanish.com
https://www.blocked.org.uk/control/ispreports/Sky/http://uploadfiles.io
https://www.blocked.org.uk/control/ispreports/Sky/http://www.cyberghostvpn.com/en_us
https://www.blocked.org.uk/control/ispreports/Three/http://www.cyberghostvpn.com/en_us
https://www.blocked.org.uk/control/ispreports/Vodafone/http://www.cyberghostvpn.com/en_us
https://www.blocked.org.uk/control/ispreports/Sky/http://www.westernmatch.com

**Comment by dantheta** [comment]
These appear to have all been bounces from sky's case handling system.  There was something a bit weird about the character encoding in the bounces.  It's been worked around in the lower-level email handling.

These all seem to open now.
