### ISSUE TITLE
Make it so ISP reports can't be closed out unless they are 30 days old

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#149]
To prevent mistaken premature closing of ISP reports, is it possible to make it so the option to close a report is not available until the report is at least 30 days old?

**Comment by dantheta** [comment]
The report close options (accept/reject/no-decision) are now invisible on the ISP report page for reviewers, until the report is older than 30 days.

**Comment by Mike-ORG** [comment]
Perfect thank you Daniel.
