### ISSUE TITLE
Website does not list blocked sites ?

### ISSUE THREAD

**Issue by gedw99** [openrightsgroup/Blocking-Middleware#164]
https://www.blocked.org.uk/blocked-sites/21246 and others do not return a list of blocked sites .

**Comment by dantheta** [comment]
Hi, thanks for getting in touch.  I think the totals for some of the lists/categories are based on blocks that were detected on older test lines.  Some of our test lines (ISP connections) have been down for a while, and the list view excludes results that aren't sufficiently fresh.

We'll be looking into it.

**Comment by dantheta** [comment]
That's fixed now - turned out to be a template error.  Thanks for letting us know!

**Comment by gedw99** [comment]
thanks @dantheta wil give it another go. :)
