### ISSUE TITLE
Overhaul auth

### ISSUE THREAD

**Issue by SimonStJG** [openrightsgroup/Blocking-Middleware#73]
The auth strategy used in the middleware HTTPS and AMQP APIs is a custom implementation of shared secrets and signatures with hmac-sha512.  Since the traffic is already going over SSL, signing bits of the payload is overkill.  The codebase could be simplified by using a standard auth strategy for the HTTPS and AMQP endpoints.

**Comment by dantheta** [comment]
There's a simplified authentication scheme on the auth-merge branch, which allows the legacy signature auth to be used, or HTTP basic (over HTTPS) as an alternative.

The authentication hasn't been done in a particularly framework-friendly way, as we're probably going to have to move off Silex at some point in the future.  The new authentication method is currently being tested, and should get merged to master pretty soon.
