### ISSUE TITLE
Remove old Vagrantfile and supporting configs

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/Blocking-Middleware#77]
Is it a problem that the URL given for the `config.vm.box_url` variable on line 18 of the [Vagrantfile](https://github.com/openrightsgroup/Blocking-Middleware/blob/master/Vagrantfile) doesn't resolve? And if that is a problem, should it be only accessible over https?

Feel free to close and ignore

**Comment by dantheta** [comment]
It's not a problem.  We basically dropped vagrant  years ago now, but haven't quite got round to tidying up its old files.  We should do that ...
