### ISSUE TITLE
Resend Cloudflare emails

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#83]
Can you let us know when the Cloudflare requests are (re) sent?

**Comment by dantheta** [comment]
That's done now.  Resending isn't a built-in feature, but it's pretty easy to do by changing the report status back to pending and retesting the URLs.

**Comment by dantheta** [comment]
It seems the new destination address for cloudflare is bouncing.

**Comment by JimKillock** [comment]
I've let them know, will see what comes back.

**Comment by JimKillock** [comment]
They ask: "Sorry about that; can you test now? Had to get IT to unblock it."

**Comment by dantheta** [comment]
They've been sent now.  No bounce notification has appeared.
