### ISSUE TITLE
Limited log in type for admin panel

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#86]
Can we create a log in type that only allows certain elements?

For now this would be aimed at reviewers. So access would be 

1.  Show ISP reports only, 
2. No access to site category options;
3. No access to reporter category options (if that is available);
4. No access to damage category options.

We will assign this category to volunteers to do reviews.

**Comment by dantheta** [comment]
Does this look OK?  The top-level menu has been restricted, and the reporter & damage category tabs have been hidden.  

Features still accessible:
* Closing reports (based on ISP acceptance/rejection)
* Access to the matches/does not match ISP policy,  
* flagging blocks as harmless/egregious/featured 
![Screenshot_2020-10-11_15-09-33](https://user-images.githubusercontent.com/398205/95680868-6aefba00-0bd4-11eb-9770-92d2639451f8.png)

**Comment by JimKillock** [comment]
Thank you Dan; I now see my description was not as clear as it should have been. For these:

2 No access to site category options;
3 No access to reporter category options (if that is available);
4 No access to damage category options.

I meant that, they should not be able to edit these elements, but should be able to assign.

**Comment by dantheta** [comment]
This has been deployed.

Users  can be created with "reviewer" access level in the usual user management control panel.

In the report/damage category tabs, reviewers can assign existing categories but cannot create new categories.

**Comment by Mike-ORG** [comment]
Excellent.

**Comment by JimKillock** [comment]
Thank you Dan @Mike-ORG Can you take a look and check how it works?

**Comment by Mike-ORG** [comment]
Yes I will have a look.

**Comment by JimKillock** [comment]
@Mike-ORG Are you happy? Let is know so we can close the ticket.

**Comment by Mike-ORG** [comment]
I'm happy thanks, the reviewer login appears to have the right functions & access for the volunteer stats update project.
