### ISSUE TITLE
Review markers on ISP review page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#87]
Distinguish between "Machine review" (ie, machine has decided the site was miscategorised) vs human review (ie, person has completed a review of the complaint). 

A human can be regarded as having reviewed the complaint when the necessary fields are all completed, ie, 

1. Category
2. Reporter Category
3. Blocked matched / did not match policy

This will ensure that human reviewers can find and complete the reviews for each complaint.

**Comment by dantheta** [comment]
I've separated out the user review columns and the automated markers on the ISP reports list.  The URL status column is only checked when the unblock is detected by the system, and the checkmark in the replies column is only shown when "matches policy" (and later the category fields) are populated by a user.  That field used to be set (matches policy=false) when an unblock was programmatically detected.  I'll try resetting the field based on the other user fields.

**Comment by dantheta** [comment]
Related: #98

**Comment by JimKillock** [comment]
I think this can be closed?

**Comment by Mike-ORG** [comment]
Fine by me.
