### ISSUE TITLE
BBFC listing as network is misleading

### ISSUE THREAD

**Issue by Mike-ORG** [openrightsgroup/Blocking-Middleware#89]
On the statistics page, the BBFC is listed until the "Network/Year" section under "ISP Responses to reports" as well as "Reply stats by ISP". 

This is misleading because BBFC is not an ISP/network. Could the BBFC be listed separately?

**Comment by dantheta** [comment]
Updated to remove BBFC from the report (similar to the ORG pseudo-ISP)

**Comment by Mike-ORG** [comment]
Thanks Daniel.
