### ISSUE TITLE
Add search for report by URL

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#95]
Add ability to find a (set of admin) reports by URL to main page. This will allow quicker finding of reports to file for appeal etc

**Comment by dantheta** [comment]
There's now a URL  search in the isp reports admin.  It can be used to search for substrings as well.  To reset a url search filter, just empty the text box and click "go".

**Comment by JimKillock** [comment]
Thanks Dan, I tried but it didn't work for me: I tried a few URLs from the list first page, but the filter excluded all sites. Can you take another look?

**Comment by dantheta** [comment]
That's strange. It works for substrings like "surf", but doesn't like having the scheme on the front. I'll look at that tonight.

**Comment by JimKillock** [comment]
Not sure if you made changes but it seems to be working now? So I think I will close it.
