### ISSUE TITLE
Add facility to upload Nominet updates

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#97]
Add facility for an admin user to upload Nominet domain names for queuing and checking.

**Comment by dantheta** [comment]
Is this superceded by #102 ?

**Comment by JimKillock** [comment]
Yes I would say so

**Comment by dantheta** [comment]
I think this is covered by the bulk upload in the admin panel.  The domain list from the nominet data would still require a bit of reformatting (adding `http://` to the front and removing the trailing `.`), but after that it will go straight in.  The commandline importers can also handle these.

**Comment by dantheta** [comment]
See also #91.  There's a daily diff of the nominet zone files running now, which will add new uk registry domains each day.  We can resubmit each of those entries after 7 & 30 days.
