### ISSUE TITLE
Speed site up for volunteers to use

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/Blocking-Middleware#99]
Change hosting arrangements so we can speed up site responsiveness so we can get volunteers working on the site classifications.

**Comment by dantheta** [comment]
I've found one badly behaved cache script that was negatively impacted by index changes at the beginning of december.  I've cut its frequency down to once per day (from 6 times per hour!).

It's the script that generates the saved list summary table on https://www.blocked.org.uk/sites

There are still some more optimizations, but this should improve it a lot for starters.

**Comment by Mike-ORG** [comment]
I haven't had any problems with the site's speed, happy to close this ticket.

**Comment by dantheta** [comment]
Many thanks!
